### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by mikolalysenko** [hughsk/bezier#1]
First, it might make more sense to cache intermediate generated code and reuse.  If you do this you could simplify the API to just  `require("bezier")(points, t)`

Second, you should evaluate the curve using de Cateljau's algorithm:

http://en.wikipedia.org/wiki/De_Casteljau's_algorithm

Not by direct summing polynomials, which is both less efficient and badly behaved numerically.

**Comment by hughsk** [comment]
Ah awesome, thanks for the heads up! Using de Cateljau's algorithm now, which gives a pretty good speed boost. The results are off by a miniscule amount (~`1e-10`) compared to before but that's fine by me. May have been the way I implemented it?

Also made the main exported function simpler because it's a little friendlier. Published as `v0.1.0` :)

**Comment by hughsk** [comment]
Fixed this a while ago, closing :)
